# automatically runs tests upon push or pr to main

name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    
    - name: Install package and test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov codecov reddit-data-collector
    
    - name: Test with pytest
      env: 
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        USER_AGENT: ${{ secrets.USER_AGENT }}
      run: |
        pytest tests/tests.py --cov=src/reddit_data_collector --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
